import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReactQueryProvider from "@/utils/providers/ReactQueryProvider";
import "./globals.css";
import { SearchProvider } from "@/utils/contexts/searchContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <SearchProvider>
            <main>{children}</main>
          </SearchProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
